import { Order } from "./types";

export const INITIAL_MOCK_ORDERS: Order[] = [
  {
    id: "ORD-9024",
    customer: {
      name: "Vikram Malhotra",
      email: "vikram.malhotra@gmail.com",
      phone: "+91 98201 44820",
      address: "Flat 402, Sea Green Heights, Worli Sea Face",
      city: "Mumbai",
      state: "Maharashtra",
      pincode: "400018",
    },
    createdAt: "2026-10-07T14:35:00Z",
    formattedDate: "Oct 7, 2026",
    formattedTime: "02:35 PM",
    items: [
      {
        id: "prod-1",
        name: "Xenon Matrix H11 LED Headlights",
        sku: "LED-H11-001",
        quantity: 2,
        unitPrice: 2499,
        totalPrice: 4998,
        image: "/images/category_lighting.jpg",
      },
    ],
    itemCount: 2,
    totalAmount: 4998,
    paymentMethod: "UPI / QR Code",
    paymentStatus: "Paid",
    orderStatus: "Processing",
    notes: "Please pack with extra bubble wrap for fragile lighting lenses.",
  },
  {
    id: "ORD-9023",
    customer: {
      name: "Arjun Patel",
      email: "arjun.patel@outlook.com",
      phone: "+91 98452 11928",
      address: "14B, Royal Palm Enclave, Koramangala 4th Block",
      city: "Bengaluru",
      state: "Karnataka",
      pincode: "560034",
    },
    createdAt: "2026-10-07T11:20:00Z",
    formattedDate: "Oct 7, 2026",
    formattedTime: "11:20 AM",
    items: [
      {
        id: "prod-2",
        name: 'Ultra-Beam 32" Curved Roof Light Bar',
        sku: "RLB-032-004",
        quantity: 1,
        unitPrice: 4999,
        totalPrice: 4999,
        image: "/images/category_lighting.jpg",
      },
      {
        id: "prod-7",
        name: "Dual-Tone Amber Fog Lamp Kit",
        sku: "FOG-AMB-002",
        quantity: 1,
        unitPrice: 1799,
        totalPrice: 1799,
        image: "/images/category_lighting.jpg",
      },
    ],
    itemCount: 2,
    totalAmount: 6798,
    paymentMethod: "Credit / Debit Card",
    paymentStatus: "Paid",
    orderStatus: "Confirmed",
    notes: "Customer requested installation bracket inclusion.",
  },
  {
    id: "ORD-9022",
    customer: {
      name: "Priya Sundaram",
      email: "priya.sundaram@gmail.com",
      phone: "+91 94440 88219",
      address: "No. 8, Anna Nagar 2nd Avenue, Near Roundtana",
      city: "Chennai",
      state: "Tamil Nadu",
      pincode: "600040",
    },
    createdAt: "2026-10-07T09:15:00Z",
    formattedDate: "Oct 7, 2026",
    formattedTime: "09:15 AM",
    items: [
      {
        id: "prod-3",
        name: "Smoked LED Tail Light Assembly",
        sku: "TAIL-SMK-003",
        quantity: 1,
        unitPrice: 3299,
        totalPrice: 3299,
        image: "/images/category_lighting.jpg",
      },
    ],
    itemCount: 1,
    totalAmount: 3299,
    paymentMethod: "UPI / QR Code",
    paymentStatus: "Pending",
    orderStatus: "Pending",
    notes: "Awaiting UPI payment confirmation callback.",
  },
  {
    id: "ORD-9021",
    customer: {
      name: "Karan Varma",
      email: "karan.varma@gmail.com",
      phone: "+91 98110 55432",
      address: "B-24, Greater Kailash 1, Near M-Block Market",
      city: "New Delhi",
      state: "Delhi",
      pincode: "110048",
    },
    createdAt: "2026-10-06T18:40:00Z",
    formattedDate: "Oct 6, 2026",
    formattedTime: "06:40 PM",
    items: [
      {
        id: "prod-4",
        name: "Android 10\" Car Stereo with CarPlay",
        sku: "STR-AND-007",
        quantity: 1,
        unitPrice: 12999,
        totalPrice: 12999,
        image: "/images/category_accessories.jpg",
      },
    ],
    itemCount: 1,
    totalAmount: 12999,
    paymentMethod: "Credit / Debit Card",
    paymentStatus: "Paid",
    orderStatus: "Shipped",
    notes: "Tracking ID: BLUEDART-84920491. Dispatched from Delhi Warehouse.",
  },
  {
    id: "ORD-9020",
    customer: {
      name: "Amitava Roy",
      email: "amitava.roy@hotmail.com",
      phone: "+91 98300 77112",
      address: "Flat 3C, Lake View Tower, Southern Avenue",
      city: "Kolkata",
      state: "West Bengal",
      pincode: "700029",
    },
    createdAt: "2026-10-06T15:10:00Z",
    formattedDate: "Oct 6, 2026",
    formattedTime: "03:10 PM",
    items: [
      {
        id: "prod-8",
        name: "Aerodynamic Carbon Mirror Caps",
        sku: "MRC-CRB-005",
        quantity: 1,
        unitPrice: 1299,
        totalPrice: 1299,
        image: "/images/category_accessories.jpg",
      },
      {
        id: "prod-6",
        name: "Premium Car Horn Set (Dual Frequency)",
        sku: "HRN-PRM-006",
        quantity: 1,
        unitPrice: 1499,
        totalPrice: 1499,
        image: "/images/category_accessories.jpg",
      },
    ],
    itemCount: 2,
    totalAmount: 2798,
    paymentMethod: "Net Banking",
    paymentStatus: "Paid",
    orderStatus: "Delivered",
    notes: "Delivered successfully on Oct 7. Signed by customer.",
  },
  {
    id: "ORD-9019",
    customer: {
      name: "Neha Sharma",
      email: "neha.sharma88@gmail.com",
      phone: "+91 97170 33819",
      address: "House 112, Sector 15, Urban Estate",
      city: "Gurugram",
      state: "Haryana",
      pincode: "122001",
    },
    createdAt: "2026-10-06T12:05:00Z",
    formattedDate: "Oct 6, 2026",
    formattedTime: "12:05 PM",
    items: [
      {
        id: "prod-5",
        name: "RGB Underglow Neon Kit with Wireless App",
        sku: "UND-RGB-010",
        quantity: 1,
        unitPrice: 3499,
        totalPrice: 3499,
        image: "/images/category_lighting.jpg",
      },
    ],
    itemCount: 1,
    totalAmount: 3499,
    paymentMethod: "UPI / QR Code",
    paymentStatus: "Paid",
    orderStatus: "Processing",
  },
  {
    id: "ORD-9018",
    customer: {
      name: "Rohan Mehra",
      email: "rohan.mehra@yahoo.co.in",
      phone: "+91 98220 99401",
      address: "Plot 45, Baner Hill Residency, Baner",
      city: "Pune",
      state: "Maharashtra",
      pincode: "411045",
    },
    createdAt: "2026-10-05T17:30:00Z",
    formattedDate: "Oct 5, 2026",
    formattedTime: "05:30 PM",
    items: [
      {
        id: "prod-9",
        name: "BassPro 12-inch Active Subwoofer Box",
        sku: "SUB-BAS-011",
        quantity: 1,
        unitPrice: 7999,
        totalPrice: 7999,
        image: "/images/category_accessories.jpg",
      },
    ],
    itemCount: 1,
    totalAmount: 7999,
    paymentMethod: "Credit / Debit Card",
    paymentStatus: "Paid",
    orderStatus: "Delivered",
  },
  {
    id: "ORD-9017",
    customer: {
      name: "Ananya Rao",
      email: "ananya.rao@gmail.com",
      phone: "+91 98490 12837",
      address: "Villa 19, Jubilee Hills Road No. 36",
      city: "Hyderabad",
      state: "Telangana",
      pincode: "500033",
    },
    createdAt: "2026-10-05T10:15:00Z",
    formattedDate: "Oct 5, 2026",
    formattedTime: "10:15 AM",
    items: [
      {
        id: "prod-10",
        name: "Chrome Door Handle Covers Set of 4",
        sku: "DHC-CHM-012",
        quantity: 1,
        unitPrice: 849,
        totalPrice: 849,
        image: "/images/category_accessories.jpg",
      },
    ],
    itemCount: 1,
    totalAmount: 849,
    paymentMethod: "Cash on Delivery (COD)",
    paymentStatus: "Failed",
    orderStatus: "Cancelled",
    notes: "Customer cancelled due to incorrect vehicle model ordered.",
  },
  {
    id: "ORD-9016",
    customer: {
      name: "Siddharth Nair",
      email: "sid.nair@rediffmail.com",
      phone: "+91 98470 66209",
      address: "TC 14/204, Panampilly Nagar, Main Avenue",
      city: "Kochi",
      state: "Kerala",
      pincode: "682036",
    },
    createdAt: "2026-10-04T16:22:00Z",
    formattedDate: "Oct 4, 2026",
    formattedTime: "04:22 PM",
    items: [
      {
        id: "prod-11",
        name: "Cat-Back Stainless Exhaust System",
        sku: "EXH-SSB-016",
        quantity: 1,
        unitPrice: 18499,
        totalPrice: 18499,
        image: "/images/category_accessories.jpg",
      },
    ],
    itemCount: 1,
    totalAmount: 18499,
    paymentMethod: "Credit / Debit Card",
    paymentStatus: "Paid",
    orderStatus: "Delivered",
  },
  {
    id: "ORD-9015",
    customer: {
      name: "Deepak Choudhary",
      email: "deepak.c@gmail.com",
      phone: "+91 94140 77218",
      address: "B-12, Vaishali Nagar, Near National Handloom",
      city: "Jaipur",
      state: "Rajasthan",
      pincode: "302021",
    },
    createdAt: "2026-10-04T11:45:00Z",
    formattedDate: "Oct 4, 2026",
    formattedTime: "11:45 AM",
    items: [
      {
        id: "prod-1",
        name: "Xenon Matrix H11 LED Headlights",
        sku: "LED-H11-001",
        quantity: 1,
        unitPrice: 2499,
        totalPrice: 2499,
        image: "/images/category_lighting.jpg",
      },
      {
        id: "prod-12",
        name: "Projector Headlight Assembly with Halo DRL",
        sku: "HDL-PRJ-009",
        quantity: 1,
        unitPrice: 8499,
        totalPrice: 8499,
        image: "/images/category_lighting.jpg",
      },
    ],
    itemCount: 2,
    totalAmount: 10998,
    paymentMethod: "UPI / QR Code",
    paymentStatus: "Paid",
    orderStatus: "Delivered",
  },
  {
    id: "ORD-9014",
    customer: {
      name: "Manoj Deshmukh",
      email: "manoj.deshmukh@gmail.com",
      phone: "+91 98230 44910",
      address: "Flat 201, Shanti Niketan, Shivaji Park",
      city: "Mumbai",
      state: "Maharashtra",
      pincode: "400028",
    },
    createdAt: "2026-10-03T14:15:00Z",
    formattedDate: "Oct 3, 2026",
    formattedTime: "02:15 PM",
    items: [
      {
        id: "prod-13",
        name: "Adjustable Coilover Suspension Kit",
        sku: "SUS-COI-018",
        quantity: 1,
        unitPrice: 22999,
        totalPrice: 22999,
        image: "/images/category_accessories.jpg",
      },
    ],
    itemCount: 1,
    totalAmount: 22999,
    paymentMethod: "Net Banking",
    paymentStatus: "Paid",
    orderStatus: "Delivered",
  },
  {
    id: "ORD-9013",
    customer: {
      name: "Tanya Kapoor",
      email: "tanya.kapoor@gmail.com",
      phone: "+91 99990 12112",
      address: "C-9, Defence Colony, Flyover Market Side",
      city: "New Delhi",
      state: "Delhi",
      pincode: "110024",
    },
    createdAt: "2026-10-03T09:40:00Z",
    formattedDate: "Oct 3, 2026",
    formattedTime: "09:40 AM",
    items: [
      {
        id: "prod-14",
        name: "Ultra-Hydrophobic Ceramic Coating Kit (50ml)",
        sku: "CAR-CRM-022",
        quantity: 2,
        unitPrice: 2699,
        totalPrice: 5398,
        image: "/images/category_accessories.jpg",
      },
    ],
    itemCount: 2,
    totalAmount: 5398,
    paymentMethod: "UPI / QR Code",
    paymentStatus: "Paid",
    orderStatus: "Delivered",
  },
  {
    id: "ORD-9012",
    customer: {
      name: "Rajesh Kulkarni",
      email: "rajesh.k@gmail.com",
      phone: "+91 98810 55120",
      address: "Plot 88, Viman Nagar, Near Phoenix Marketcity",
      city: "Pune",
      state: "Maharashtra",
      pincode: "411014",
    },
    createdAt: "2026-10-02T16:00:00Z",
    formattedDate: "Oct 2, 2026",
    formattedTime: "04:00 PM",
    items: [
      {
        id: "prod-15",
        name: "Heavy-Duty All-Terrain 18-inch Tires",
        sku: "TIR-ATR-024",
        quantity: 2,
        unitPrice: 11499,
        totalPrice: 22998,
        image: "/images/category_tires.jpg",
      },
    ],
    itemCount: 2,
    totalAmount: 22998,
    paymentMethod: "Credit / Debit Card",
    paymentStatus: "Paid",
    orderStatus: "Delivered",
  },
  {
    id: "ORD-9011",
    customer: {
      name: "Gaurav Sen",
      email: "gaurav.sen@gmail.com",
      phone: "+91 98450 33910",
      address: "12th Cross, Indiranagar 1st Stage",
      city: "Bengaluru",
      state: "Karnataka",
      pincode: "560038",
    },
    createdAt: "2026-10-02T11:10:00Z",
    formattedDate: "Oct 2, 2026",
    formattedTime: "11:10 AM",
    items: [
      {
        id: "prod-7",
        name: "Dual-Tone Amber Fog Lamp Kit",
        sku: "FOG-AMB-002",
        quantity: 1,
        unitPrice: 1799,
        totalPrice: 1799,
        image: "/images/category_lighting.jpg",
      },
    ],
    itemCount: 1,
    totalAmount: 1799,
    paymentMethod: "UPI / QR Code",
    paymentStatus: "Paid",
    orderStatus: "Delivered",
  },
  {
    id: "ORD-9010",
    customer: {
      name: "Aditya Bhatia",
      email: "aditya.bhatia@gmail.com",
      phone: "+91 98100 22345",
      address: "Tower 4, Flat 1202, DLF Phase 5",
      city: "Gurugram",
      state: "Haryana",
      pincode: "122009",
    },
    createdAt: "2026-10-01T15:30:00Z",
    formattedDate: "Oct 1, 2026",
    formattedTime: "03:30 PM",
    items: [
      {
        id: "prod-2",
        name: 'Ultra-Beam 32" Curved Roof Light Bar',
        sku: "RLB-032-004",
        quantity: 1,
        unitPrice: 4999,
        totalPrice: 4999,
        image: "/images/category_lighting.jpg",
      },
    ],
    itemCount: 1,
    totalAmount: 4999,
    paymentMethod: "UPI / QR Code",
    paymentStatus: "Paid",
    orderStatus: "Delivered",
  },
  {
    id: "ORD-9009",
    customer: {
      name: "Sneha Mukherjee",
      email: "sneha.m@yahoo.com",
      phone: "+91 98310 88290",
      address: "Flat 5A, Silver Spring, EM Bypass",
      city: "Kolkata",
      state: "West Bengal",
      pincode: "700105",
    },
    createdAt: "2026-10-01T10:00:00Z",
    formattedDate: "Oct 1, 2026",
    formattedTime: "10:00 AM",
    items: [
      {
        id: "prod-6",
        name: "Premium Car Horn Set (Dual Frequency)",
        sku: "HRN-PRM-006",
        quantity: 2,
        unitPrice: 1499,
        totalPrice: 2998,
        image: "/images/category_accessories.jpg",
      },
    ],
    itemCount: 2,
    totalAmount: 2998,
    paymentMethod: "Cash on Delivery (COD)",
    paymentStatus: "Pending",
    orderStatus: "Pending",
  },
  {
    id: "ORD-9008",
    customer: {
      name: "Suresh Pillai",
      email: "suresh.pillai@gmail.com",
      phone: "+91 94470 11982",
      address: "House 22, Jawahar Nagar, Kowdiar",
      city: "Thiruvananthapuram",
      state: "Kerala",
      pincode: "695003",
    },
    createdAt: "2026-09-30T17:15:00Z",
    formattedDate: "Sep 30, 2026",
    formattedTime: "05:15 PM",
    items: [
      {
        id: "prod-4",
        name: "Android 10\" Car Stereo with CarPlay",
        sku: "STR-AND-007",
        quantity: 1,
        unitPrice: 12999,
        totalPrice: 12999,
        image: "/images/category_accessories.jpg",
      },
    ],
    itemCount: 1,
    totalAmount: 12999,
    paymentMethod: "Credit / Debit Card",
    paymentStatus: "Paid",
    orderStatus: "Processing",
  },
  {
    id: "ORD-9007",
    customer: {
      name: "Harish Goud",
      email: "harish.goud@gmail.com",
      phone: "+91 99890 44210",
      address: "Plot 104, Madhapur, Near Cyber Towers",
      city: "Hyderabad",
      state: "Telangana",
      pincode: "500081",
    },
    createdAt: "2026-09-29T12:40:00Z",
    formattedDate: "Sep 29, 2026",
    formattedTime: "12:40 PM",
    items: [
      {
        id: "prod-8",
        name: "Aerodynamic Carbon Mirror Caps",
        sku: "MRC-CRB-005",
        quantity: 1,
        unitPrice: 1299,
        totalPrice: 1299,
        image: "/images/category_accessories.jpg",
      },
    ],
    itemCount: 1,
    totalAmount: 1299,
    paymentMethod: "Net Banking",
    paymentStatus: "Failed",
    orderStatus: "Cancelled",
    notes: "Payment failed at gateway and customer abandoned checkout.",
  },
  {
    id: "ORD-9006",
    customer: {
      name: "Manpreet Singh",
      email: "manpreet.singh@gmail.com",
      phone: "+91 98760 11200",
      address: "SCF 24, Phase 7, SAS Nagar",
      city: "Mohali",
      state: "Punjab",
      pincode: "160062",
    },
    createdAt: "2026-09-28T14:20:00Z",
    formattedDate: "Sep 28, 2026",
    formattedTime: "02:20 PM",
    items: [
      {
        id: "prod-3",
        name: "Smoked LED Tail Light Assembly",
        sku: "TAIL-SMK-003",
        quantity: 2,
        unitPrice: 3299,
        totalPrice: 6598,
        image: "/images/category_lighting.jpg",
      },
    ],
    itemCount: 2,
    totalAmount: 6598,
    paymentMethod: "UPI / QR Code",
    paymentStatus: "Paid",
    orderStatus: "Delivered",
  },
  {
    id: "ORD-9005",
    customer: {
      name: "Abhishek Joshi",
      email: "abhishek.j@gmail.com",
      phone: "+91 98260 55190",
      address: "18, South Tukoganj, Near Treasure Island",
      city: "Indore",
      state: "Madhya Pradesh",
      pincode: "452001",
    },
    createdAt: "2026-09-27T09:50:00Z",
    formattedDate: "Sep 27, 2026",
    formattedTime: "09:50 AM",
    items: [
      {
        id: "prod-5",
        name: "RGB Underglow Neon Kit with Wireless App",
        sku: "UND-RGB-010",
        quantity: 1,
        unitPrice: 3499,
        totalPrice: 3499,
        image: "/images/category_lighting.jpg",
      },
    ],
    itemCount: 1,
    totalAmount: 3499,
    paymentMethod: "UPI / QR Code",
    paymentStatus: "Pending",
    orderStatus: "Pending",
  },
];
